### ISSUE TITLE
ListView Repeating Data

### ISSUE THREAD

**Issue by Danatorr** [Danatorr/Rpg-Companion#1]
I'm building an Initiative Tracker app by my self to test my basic knowledge of Flutter.

The app only has 2 screens, the main screen that has a ListView with InitiativeInherited.of(context).initiativeList as a child and the second screen is a "add new initiative screen".

initiativeList is a List of type InitiativeCard, which is a StatefulWidget.

initiativeList is being sorted from highest to lowest initiativeNumber, however, it doesn't work as expected when it's shown in the ListView, instead of showing the newly added initiatives in the correct order, it "fake adds" the lowest initiativeNumber element.

For Example:

I added from Test_5 with value 5 to Test_3 with value 3, but when I tried adding Test_6 with value 6, it just repeated Test_3, which was the lowest number at the time, but it was able to add a Test_1 with value 1, which is very strange...

<img width="154" alt="mU19b" src="https://github.com/Danatorr/Rpg-Companion/assets/20666482/8b62b8d3-921a-43ff-9f69-58f78e760ff4">

I've tried many things, like changing the add initiative logic and debugging the sort method, but it all checks out for me.

```
   void addInitiative(String name, int initiativeNumber) {
     initiativeList.add(InitiativeCard(key: UniqueKey(), name: name, initiativeNumber: initiativeNumber, ));

     print(initiativeList.first.initiativeNumber);
     initiativeList.sort((a, b) => b.initiativeNumber.compareTo(a.initiativeNumber));
     print(initiativeList.first.initiativeNumber);
  }
```

I've searched for hours and I think the answer is to use Keys, but I can't seem to get them to work the way I want, even after watching many tutorials and reading the documentations.

This is the constructor for InitiativeCard:

```
  const InitiativeCard({required Key key, required this.name, required this.initiativeNumber})
      : super(key: key);
This is the ListView:
```

I've even dabbled with Builders, but it still wouldn't work.

body: Center(
        child: ListView(
          children:  InitiativeInherited.of(context).initiativeList,
        ),
      ),

**Comment by jamal-o** [comment]
Hello @Danatorr !

I'm also learning flutter and decided to lend a helping hand. Here are the two things I changed. 

**1. I changed the ListView to a ListView.builder in initiativeTrackerScreen.dart**  

child: ListView.builder(
          itemCount:  InitiativeInherited.of(context).initiativeList.length,
          itemBuilder: (context, index) =>  InitiativeInherited.of(context).initiativeList[index],
        ),

**2. I changed the updatShouldNotify function in initiative_inherited.dart**
bool updateShouldNotify(InitiativeInherited oldWidget) {
    bool listUpdated = !listEquals(oldWidget.initiativeList, initiativeList);
    bool listAddedTo = oldWidget.initiativeList.length != initiativeList.length;
    if (listUpdated || listAddedTo)
      return true;
    else
      return false;
  }

Also, I used a callback to invoke the setState function of the tracker screen in the onPressed function of the newCard screen before popping the screen. I used this to update the state in a quick way - you might want to implement this in a different way. 

P.s I can share the files if you need them. Cheers!
